#ifndef DISPLAY_H
#define DISPLAY_H

#define CELL_SIZE 100
#define CELL_MARGIN 5
#define GRID_SIZE ((CELL_SIZE * 9) + 8 + 4)
#define FONT_SIZE (CELL_SIZE - CELL_MARGIN * 2)
#define LITTLE_FONT_SIZE (FONT_SIZE / 3)
#define WINDOW_WIDTH (GRID_SIZE)
#define WINDOW_HEIGHT (GRID_SIZE)

#endif